version: "3"



services:
  spring-boot:
    container_name: spring-boot
    image: kids-in-seoul-api
    depends_on:
      - redis
    ports:
      - "8080:8080"
    restart: always
    networks:
      - kis_network
    environment:
      SPRING_DATASOURCE_URL: endpoint
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: passwd
      SPRING_PROFILES_ACTIVE: dev

  flask:
    container_name: flask
    image: kids-in-seoul-flask
    ports:
      - "5000:5000"
    restart: always
    networks:
      - kis_network

  redis:
    image: redis:alpine
    command: redis-server --port 6369
    container_name: redis_boot
    hostname: redis_boot
    labels:
      - "name=redis"
      - "mode=standalone"
    ports:
      - "6379:6379"
    networks:
      - kis_network

  react:
    image: kids-in-seoul-front


  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - spring-boot
      - flask
    restart: always


networks:
  kis_network:
